### ISSUE TITLE
Java does not find C++ binaries

### ISSUE THREAD

**Issue by cernoch** [master-keying/mks#2]
Java code expects binaries to be found in `target/binary/*`. Shall the Java code be changed? If so, what should be the **default** path for binaries?

After a fix, `mvn test` will work again.

**Comment by horenmar** [comment]
This is hard to answer, because C++ _should_ be built out-of-tree, and a developer can reasonably expect to have multiple build folders at the same time, using different configurations (e.g. fully optimized Release versus Debug versus Release with Debug symbols). This means that at any point in time, the developer can expect to have multiple valid binaries compiled. On the other hand, because of JIT, Java usually expects to have only one set of build artifacts per project.

As I see it, there are three ways of dealing with this.

1) Standardize a single place where Java looks for C++ binaries, and tell the user to copy the built binaries there. This is not a really good option.

2) Standardize a single place where Java looks for C++ binaries, and add a post-build step to CMake that copies the binaries there. This would mean that last-built set of binaries would be used, which can be a bit of a mess, but is likely to work reasonably well.

3) Have Java use environment variables when looking for the C++ binaries. A path could then be standardized to `target/binary/*`, but user could do say `MKS_BINARY_DIR=build-release` and Java parts would look into `build-release/target/binary`.

**Comment by cernoch** [comment]
The simplest solution so far is a mixed approach

1. Linux users are advised to update their `PATH`.
2. Windows users are advised to copy binaries into the _project root directory_.

When Java calls e.g. `diagonal`,

1. on Linux, the binary is found on the `PATH`.
2. Windows finds `diagonal.exe` in the current directory.

This works, because:

1. On Linux, `./` prefix does not need to be added if the binary is on the PATH.
2. On Windows, `.exe` suffix is automatically added by the OS.

Pros and cons:

* The Java part is completely OS-independent.
* Updating `PATH` is cumbersome. At least, it's only needed on Linux.
