### ISSUE TITLE
AppVeyor test succeeds despite a test failure

### ISSUE THREAD

**Issue by cernoch** [master-keying/mks#49]
I've noticed in one of the logs:
https://ci.appveyor.com/project/horenmar/mks/build/590/job/doa9ujwx02jfy7kp#L2165
that ctest has failed, but the entire build has a green light.

Maybe this has something to do with 899a2e817702d573a976cc7c1d3e4e97dc434260.

Martin, could you have a look at this, please?

**Comment by horenmar** [comment]
There are some problems with the tests on AppVeyor in general.

When a test runs into a failing assertion, it hangs, as the JIT debugger pops out a dialog to ask the user whether they want to debug the binary. Except, there is no user to answer the dialog on AppVeyor... This is compounded by the above-mentioned problem, where CTest then decides that this test somehow succeeded.

**Comment by horenmar** [comment]
Ok, I should be able to solve at least part of it, but the batch file is getting uglier and uglier.

The problem is a combination of 2 facts
* Batch file doesn't have a concept of "Abort on failed command"
* Batch file's return code is implicitly the return code of the last command

This means that if the C++ tests fail, but the Java ones succeed, then the return code is 0.

**Comment by cernoch** [comment]
I've started a mini side-project and eventually had rewritten everything to PowerShell:
https://github.com/cernoch/boolSATlib/blob/master/misc/appveyor/library.ps1

This issue is resolved there. Shall we adapt the script here?

The only remaining bit to rewrite is the `coverage-helper`...

**Comment by horenmar** [comment]
I need to do some testing on mem check indirection interaction with ctest, but I see no reason not to convert the scripts to PS.

**Comment by horenmar** [comment]
I figured out what is wrong with coverage-helper.

The trick is that `pclose` returns the return code _left-shifted_ by 8. This means that if the underlying call returns e.g. 1, the return code received by coverage-helper is 256. It then passes that return code outside to CTest... But CTest only checks the bottom 8 bits of return code and ignores the upper bits, so CTest always sees 0 as the return value.

**Comment by horenmar** [comment]
And I also figured out what was wrong with the batch script exit. Did you know, that Batch replaces all variables with their values at the time of _parsing_ and not at the time they are executed? In other words, this:
```batch
return-1.exe || exit /b %ERRORLEVEL%
return-0.exe || exit /b %ERRORLEVEL%
```
will properly exit after the first line, but it will exit with success because the `%ERRORLEVEL%` is replaced with value when the script is parsed, at which time it is most likely a 0.

974fbddc8910f84bd0435106415a0a34edc8c846 shows how to fix it.
